pipeline{
    agent {
        label "Slave"
    }
    environment {
        SAMPLE_GLOBAL_ENV_VAR = "This is a global environment variable"
        SAMPLE_ENV = credentials("simple-secret-text") // This is a secret text credential defined in Jenkins
        //  The credentials() function is used to retrieve credentials stored in Jenkins.
//  The credentials() helper:

// Injects the secret into the environment.

// Is commonly used for:

// Secret text

// Username/password

// SSH keys, etc.

// In this case, you're retrieving a Secret Text credential.
    }
    stages {
        stage("Run EnV Global") {
            steps{
                echo "SAMPLE_GLOBAL_ENV_VAR"
                echo "$SAMPLE_GLOBAL_ENV_VAR"
            }
        }
        stage("RUn Local")
        {
            environment {
                SAMPLE_LOCAL_ENV_VAR = "This is a local environment variable"
            }
            steps{
                echo "This is a local environment variable"
                echo "$SAMPLE_LOCAL_ENV_VAR"
            }
        }
        stage("FInal multiple way") {
            steps{
                echo "This is a final stage with multiple ways to define environment variables"
                echo "${SAMPLE_GLOBAL_ENV_VAR}"
                echo " ${env.SAMPLE_GLOBAL_ENV_VAR}"
            }
        }
        stage("Release"){
            steps {
                echo "This is the release stage"
                sh 'echo "Using secret in shell: $SAMPLE_ENV" > /dev/null'
                //  sh 'example --secret $SAMPLE_ENV'
            }
        }
    }
}